# Generated by Django 3.2.16 on 2023-10-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('#03c03c', 'Завтрак'), ('#ff6347', 'Обед'), ('#120a8f', 'Ужин')], max_length=16, unique=True, verbose_name='Цветовой код'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients_ingredients', to='recipes.ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
