# Generated by Django 3.2.16 on 2023-10-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientsamount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsamount',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
