# Generated by Django 3.2.16 on 2023-10-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20231018_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='favorites',
            new_name='recipe',
        ),
    ]
