version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data 
  
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - static:/static
      - media:/app/media
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    build: ./nginx/
    env_file: .env
    depends_on:
      - frontend
    ports:
      - 8000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media