version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mralmostfreeman/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    image: mralmostfreeman/foodgram_frontend:latest
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: mralmostfreeman/foodgram_infra:latest
    env_file: .env
    ports:
      - 9099:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend