# Generated by Django 3.2.16 on 2023-10-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_favourites_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='favourite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_recipe', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
