# Generated by Django 3.2.16 on 2023-10-18 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20231017_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favourite',
            name='favorites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='recipes.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#03c03c', 'Зеленый'), ('#ff6347', 'Красный'), ('#120a8f', 'Синий')], max_length=7, verbose_name='Цветовой код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Уникальный слаг'),
        ),
    ]
