# Generated by Django 3.2.16 on 2023-10-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_rename_favorites_favourite_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsamount',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
