# Generated by Django 3.2.3 on 2023-11-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20231119_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pub_date',
        ),
    ]
